### ISSUE TITLE
Readme code fails

### ISSUE THREAD

**Issue by TanguyBarthelemy** [AQLT/ggdemetra3#2]
I tried your readme code example:

```r
library("ggdemetra3")

spec <- rjd3x13::spec_x13("rsa3") |> 
    rjd3toolkit::set_tradingdays(option = "WorkingDays")

p_ipi_fr <- ggplot(data = ipi_c_eu_df[, c("date", "FR")], mapping = aes(x = date, y = FR)) +
    geom_sa(component = "y_f(12)", spec = spec)
```

But it returns an error:

```
> Warning message:
> Computation failed in `stat_sa()`
> Caused by error in `.jcall()`:
> ! method process with signature (Ljdplus/toolkit/base/api/timeseries/TsData;Ljdplus/x13/base/api/x13/X13Spec;Ljdplus/toolkit/base/api/timeseries/regression/ModellingContext;)Ljdplus/x13/base_core/x13/X13Results; not found 
```

Maybe it's due to recent update of the java code from other rjd3 packages. Do you have a commit number that would allow a working installation? It's just to test your package and make some plots.

Thank you!

**Comment by AQLT** [comment]
Try using my fork of rjd3x13: https://github.com/AQLT/rjd3x13. I fixed an issue of `jx13`  in https://github.com/AQLT/rjd3x13/commit/3a3d656a8c304a2b2f5c50420be476b1ba7c6d15 but it is not yet merged in the main repo of rjd3x13.
That's why in the GitHub action the installation of rjd3x13 is made from my fork:
https://github.com/AQLT/ggdemetra3/blob/4e89760efa846c3c7238a986ec096b0300a0fb2f/.github/workflows/R-CMD-check.yaml#L81

**Comment by TanguyBarthelemy** [comment]
I should have noticed that! Thank you
